### ISSUE TITLE
【Chapter 2 Review】Cup with Handle を AZN で検証

### ISSUE THREAD

**Issue by shinseitaro** [fintalk/reading-How-to-Make-Money-in-Stocks#50]
[The Most Common Chart Pattern: “Cup with Handle”](https://github.com/fintalk/reading-How-to-Make-Money-in-Stocks/blob/main/contents/chapter02.md#the-most-common-chart-pattern-cup-with-handle ) を読み直して
以下の銘柄が Cup with Handle であるところを検証し、描画して説明をお願いします。

## 対象銘柄

https://finance.yahoo.com/quote/AZN?p=AZN

## TODO 

- [ ] main branch から review 用のブランチを切る（例: `review_shinseitaro`)
  - 以下の作業は切り出したブランチで行ってください
  - Chapter02.md の最後に以下を追記してレビューを書く
      ```
      ## Review 
      
      ### AZN 

      ```
- [ ] [The Most Common Chart Pattern: “Cup with Handle”](https://github.com/fintalk/reading-How-to-Make-Money-in-Stocks/blob/main/contents/chapter02.md#the-most-common-chart-pattern-cup-with-handle ) 読みなおし
- [ ] チャートを画像で保存
- [ ] 本に書いてあることと同じことが起きているところや、その他メモを書き残す
- [ ] push
- [ ] みんなに説明＆シェア（←輪読会で）
- [ ] main にマージ（←輪読会シェア後）

## メモ

銘柄は、2022/07/08 現在で、直近 8週間~9ヶ月で Cup with Handle が発生した比較的大型の米国株から選定しました。
スクリーニングしたサイトはこちらです。

https://swingtradebot.com/events/61/equities?selected_date=2022-07-08&min_vol=250000&min_price=10.0&max_price=999999.0&adx_trend=&grade=&rsi_comparator=&rsi_value1=&include_etfs=0&just_my_stocks=0&opt=0&wkly_opt=0&html_button=as_html
